/*======= Login Action =========*/
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
/*======= Customer Action =========*/
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const CUSTOMERS_ERROR = "CUSTOMERS_ERROR"
export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST"
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS"
export const CUSTOMER_LIST_FAIL = "CUSTOMER_LIST_FAIL"
export const CUSTOMER_DETAIL_REQUEST = "CUSTOMER_DETAIL_REQUEST"
export const CUSTOMER_DETAIL_SUCCESS = "CUSTOMER_DETAIL_SUCCESS"
export const CUSTOMER_DETAIL_FAIL = "CUSTOMER_DETAIL_FAIL"
export const CUSTOMER_SAVE_REQUEST = "CUSTOMER_SAVE_REQUEST"
export const CUSTOMER_SAVE_SUCCESS = "CUSTOMER_SAVE_SUCCESS"
export const CUSTOMER_SAVE_FAIL = "CUSTOMER_SAVE_FAIL"
export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST"
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS"
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL"
export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST"
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS"
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL"
/*======= User Action =========*/
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = "USERS_ERROR"
